### PR TITLE
fixedDurationIssue

### PR DESCRIPTION
**Pull request by Sumit112192**

### CODE REVIEW

**Review by arnoob16 — CHANGES_REQUESTED** [review]
Hey @Sumit112192, you've successfully solved the 0 Days issue but currently, for the `Codechef Long Challenge` it gives out `10 Days, ` instead of `10 Days.`. Fixing this would make your PR ready to be merged. 

image

**Comment by Sumit112192** [comment]
Is everything okay now?

**Comment by Sumit112192** [comment]
@arnoob16

**Review by arnoob16 — APPROVED** [review]
Good to be merged.

**Pull request merged**
